name: Build and Push Actions Runner scale-set image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "images/ubuntu/dockerfiles-scaleset/**"

  pull_request: # to test the workflow
    branches:
      - main
    paths:
      - "images/ubuntu/dockerfiles-scaleset/**"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        build_opts:
          - base_image: devzeroinc/gha-runner-image-ubuntu
            base_tag: 22.04-devel
            build_rule_name: build-ubuntu
            push_rule_name: push-ubuntu
          - base_image: devzeroinc/gha-runner-image-ubuntu
            base_tag: 24.04-devel
            build_rule_name: build-ubuntu
            push_rule_name: push-ubuntu
          - base_image: amazonlinux
            base_tag: 2023
            build_rule_name: build-fedora
            push_rule_name: push-fedora
    runs-on: ubuntu-xl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ vars.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and Push Docker image
        shell: bash
        run: |
          cd images/ubuntu/dockerfiles-scaleset
          TAG=${{ matrix.build_opts.base_tag }} BASE_IMAGE=${{ matrix.build_opts.base_image }}:${{ matrix.build_opts.base_tag}}
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            make ${{ matrix.build_opts.build_rule_name }}
          else
            make ${{ matrix.build_opts.push_rule_name }}
          fi
