name: Build and Push Actions Runner scale-set image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "images/ubuntu/dockerfiles-scaleset/**"

  pull_request: # to test the workflow
    branches:
      - main
    paths:
      - "images/ubuntu/dockerfiles-scaleset/**"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        base_image: [22.04-devel, 24.04-devel]
    runs-on: ubuntu-xl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ vars.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and Push Docker image
        shell: bash
        run: |
          cd images/ubuntu/dockerfiles-scaleset
          TAG=${{ matrix.base_image }} BASE_IMAGE=devzeroinc/gha-runner-image-ubuntu:${{ matrix.base_image}}
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            make build-image
          else
            make push
          fi
